/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: messages.proto */

#ifndef PROTOBUF_C_messages_2eproto__INCLUDED
#define PROTOBUF_C_messages_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1000000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1001001 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct _Messages__Value Messages__Value;
typedef struct _Messages__GetRequest Messages__GetRequest;
typedef struct _Messages__GetResponse Messages__GetResponse;
typedef struct _Messages__PutRequest Messages__PutRequest;
typedef struct _Messages__PutResponse Messages__PutResponse;
typedef struct _Messages__RemoveRequest Messages__RemoveRequest;
typedef struct _Messages__RemoveResponse Messages__RemoveResponse;
typedef struct _Messages__InitStackRequest Messages__InitStackRequest;
typedef struct _Messages__InitStackResponse Messages__InitStackResponse;
typedef struct _Messages__PushRequest Messages__PushRequest;
typedef struct _Messages__PushResponse Messages__PushResponse;
typedef struct _Messages__PopRequest Messages__PopRequest;
typedef struct _Messages__PopResponse Messages__PopResponse;
typedef struct _Messages__InitQueueRequest Messages__InitQueueRequest;
typedef struct _Messages__InitQueueResponse Messages__InitQueueResponse;
typedef struct _Messages__EnqueueRequest Messages__EnqueueRequest;
typedef struct _Messages__EnqueueResponse Messages__EnqueueResponse;
typedef struct _Messages__DequeueRequest Messages__DequeueRequest;
typedef struct _Messages__DequeueResponse Messages__DequeueResponse;
typedef struct _Messages__PeekRequest Messages__PeekRequest;
typedef struct _Messages__PeekResponse Messages__PeekResponse;
typedef struct _Messages__SizeRequest Messages__SizeRequest;
typedef struct _Messages__SizeResponse Messages__SizeResponse;


/* --- enums --- */

typedef enum _Messages__Error {
  MESSAGES__ERROR__NO_ERROR = 1,
  MESSAGES__ERROR__NO_VALUE = 2,
  MESSAGES__ERROR__KEY_IN_USE = 3,
  MESSAGES__ERROR__WRONG_TYPE = 4,
  MESSAGES__ERROR__EMPTY = 5,
  MESSAGES__ERROR__WRONG_VALUE = 6
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(MESSAGES__ERROR)
} Messages__Error;

/* --- messages --- */

typedef enum {
  MESSAGES__VALUE__VALUE__NOT_SET = 0,
  MESSAGES__VALUE__VALUE_STRING_VALUE = 1,
  MESSAGES__VALUE__VALUE_INT_VALUE = 2,
} Messages__Value__ValueCase;

struct  _Messages__Value
{
  ProtobufCMessage base;
  Messages__Value__ValueCase value_case;
  union {
    char *stringvalue;
    int32_t intvalue;
  };
};
#define MESSAGES__VALUE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&messages__value__descriptor) \
    , MESSAGES__VALUE__VALUE__NOT_SET, {} }


struct  _Messages__GetRequest
{
  ProtobufCMessage base;
  char *key;
};
#define MESSAGES__GET_REQUEST__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&messages__get_request__descriptor) \
    , NULL }


typedef enum {
  MESSAGES__GET_RESPONSE__RESULT__NOT_SET = 0,
  MESSAGES__GET_RESPONSE__RESULT_VALUE = 2,
  MESSAGES__GET_RESPONSE__RESULT_ERROR = 3,
} Messages__GetResponse__ResultCase;

struct  _Messages__GetResponse
{
  ProtobufCMessage base;
  char *key;
  Messages__GetResponse__ResultCase result_case;
  union {
    Messages__Value *value;
    Messages__Error error;
  };
};
#define MESSAGES__GET_RESPONSE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&messages__get_response__descriptor) \
    , NULL, MESSAGES__GET_RESPONSE__RESULT__NOT_SET, {} }


struct  _Messages__PutRequest
{
  ProtobufCMessage base;
  char *key;
  Messages__Value *value;
};
#define MESSAGES__PUT_REQUEST__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&messages__put_request__descriptor) \
    , NULL, NULL }


struct  _Messages__PutResponse
{
  ProtobufCMessage base;
  char *key;
  protobuf_c_boolean has_error;
  Messages__Error error;
};
#define MESSAGES__PUT_RESPONSE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&messages__put_response__descriptor) \
    , NULL, 0,0 }


struct  _Messages__RemoveRequest
{
  ProtobufCMessage base;
  char *key;
};
#define MESSAGES__REMOVE_REQUEST__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&messages__remove_request__descriptor) \
    , NULL }


struct  _Messages__RemoveResponse
{
  ProtobufCMessage base;
  char *key;
  protobuf_c_boolean has_error;
  Messages__Error error;
};
#define MESSAGES__REMOVE_RESPONSE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&messages__remove_response__descriptor) \
    , NULL, 0,0 }


struct  _Messages__InitStackRequest
{
  ProtobufCMessage base;
  char *key;
};
#define MESSAGES__INIT_STACK_REQUEST__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&messages__init_stack_request__descriptor) \
    , NULL }


struct  _Messages__InitStackResponse
{
  ProtobufCMessage base;
  char *key;
  protobuf_c_boolean has_error;
  Messages__Error error;
};
#define MESSAGES__INIT_STACK_RESPONSE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&messages__init_stack_response__descriptor) \
    , NULL, 0,0 }


struct  _Messages__PushRequest
{
  ProtobufCMessage base;
  char *key;
  Messages__Value *value;
};
#define MESSAGES__PUSH_REQUEST__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&messages__push_request__descriptor) \
    , NULL, NULL }


struct  _Messages__PushResponse
{
  ProtobufCMessage base;
  char *key;
  protobuf_c_boolean has_error;
  Messages__Error error;
};
#define MESSAGES__PUSH_RESPONSE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&messages__push_response__descriptor) \
    , NULL, 0,0 }


struct  _Messages__PopRequest
{
  ProtobufCMessage base;
  char *key;
};
#define MESSAGES__POP_REQUEST__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&messages__pop_request__descriptor) \
    , NULL }


typedef enum {
  MESSAGES__POP_RESPONSE__RESULT__NOT_SET = 0,
  MESSAGES__POP_RESPONSE__RESULT_VALUE = 2,
  MESSAGES__POP_RESPONSE__RESULT_ERROR = 3,
} Messages__PopResponse__ResultCase;

struct  _Messages__PopResponse
{
  ProtobufCMessage base;
  char *key;
  Messages__PopResponse__ResultCase result_case;
  union {
    Messages__Value *value;
    Messages__Error error;
  };
};
#define MESSAGES__POP_RESPONSE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&messages__pop_response__descriptor) \
    , NULL, MESSAGES__POP_RESPONSE__RESULT__NOT_SET, {} }


struct  _Messages__InitQueueRequest
{
  ProtobufCMessage base;
  char *key;
};
#define MESSAGES__INIT_QUEUE_REQUEST__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&messages__init_queue_request__descriptor) \
    , NULL }


struct  _Messages__InitQueueResponse
{
  ProtobufCMessage base;
  char *key;
  protobuf_c_boolean has_error;
  Messages__Error error;
};
#define MESSAGES__INIT_QUEUE_RESPONSE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&messages__init_queue_response__descriptor) \
    , NULL, 0,0 }


struct  _Messages__EnqueueRequest
{
  ProtobufCMessage base;
  char *key;
  Messages__Value *value;
};
#define MESSAGES__ENQUEUE_REQUEST__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&messages__enqueue_request__descriptor) \
    , NULL, NULL }


struct  _Messages__EnqueueResponse
{
  ProtobufCMessage base;
  char *key;
  protobuf_c_boolean has_error;
  Messages__Error error;
};
#define MESSAGES__ENQUEUE_RESPONSE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&messages__enqueue_response__descriptor) \
    , NULL, 0,0 }


struct  _Messages__DequeueRequest
{
  ProtobufCMessage base;
  char *key;
};
#define MESSAGES__DEQUEUE_REQUEST__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&messages__dequeue_request__descriptor) \
    , NULL }


typedef enum {
  MESSAGES__DEQUEUE_RESPONSE__RESULT__NOT_SET = 0,
  MESSAGES__DEQUEUE_RESPONSE__RESULT_VALUE = 2,
  MESSAGES__DEQUEUE_RESPONSE__RESULT_ERROR = 3,
} Messages__DequeueResponse__ResultCase;

struct  _Messages__DequeueResponse
{
  ProtobufCMessage base;
  char *key;
  Messages__DequeueResponse__ResultCase result_case;
  union {
    Messages__Value *value;
    Messages__Error error;
  };
};
#define MESSAGES__DEQUEUE_RESPONSE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&messages__dequeue_response__descriptor) \
    , NULL, MESSAGES__DEQUEUE_RESPONSE__RESULT__NOT_SET, {} }


struct  _Messages__PeekRequest
{
  ProtobufCMessage base;
  char *key;
};
#define MESSAGES__PEEK_REQUEST__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&messages__peek_request__descriptor) \
    , NULL }


typedef enum {
  MESSAGES__PEEK_RESPONSE__RESULT__NOT_SET = 0,
  MESSAGES__PEEK_RESPONSE__RESULT_VALUE = 2,
  MESSAGES__PEEK_RESPONSE__RESULT_ERROR = 3,
} Messages__PeekResponse__ResultCase;

struct  _Messages__PeekResponse
{
  ProtobufCMessage base;
  char *key;
  Messages__PeekResponse__ResultCase result_case;
  union {
    Messages__Value *value;
    Messages__Error error;
  };
};
#define MESSAGES__PEEK_RESPONSE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&messages__peek_response__descriptor) \
    , NULL, MESSAGES__PEEK_RESPONSE__RESULT__NOT_SET, {} }


struct  _Messages__SizeRequest
{
  ProtobufCMessage base;
  char *key;
};
#define MESSAGES__SIZE_REQUEST__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&messages__size_request__descriptor) \
    , NULL }


typedef enum {
  MESSAGES__SIZE_RESPONSE__RESULT__NOT_SET = 0,
  MESSAGES__SIZE_RESPONSE__RESULT_SIZE = 2,
  MESSAGES__SIZE_RESPONSE__RESULT_ERROR = 3,
} Messages__SizeResponse__ResultCase;

struct  _Messages__SizeResponse
{
  ProtobufCMessage base;
  char *key;
  Messages__SizeResponse__ResultCase result_case;
  union {
    int32_t size;
    Messages__Error error;
  };
};
#define MESSAGES__SIZE_RESPONSE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&messages__size_response__descriptor) \
    , NULL, MESSAGES__SIZE_RESPONSE__RESULT__NOT_SET, {} }


/* Messages__Value methods */
void   messages__value__init
                     (Messages__Value         *message);
size_t messages__value__get_packed_size
                     (const Messages__Value   *message);
size_t messages__value__pack
                     (const Messages__Value   *message,
                      uint8_t             *out);
size_t messages__value__pack_to_buffer
                     (const Messages__Value   *message,
                      ProtobufCBuffer     *buffer);
Messages__Value *
       messages__value__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   messages__value__free_unpacked
                     (Messages__Value *message,
                      ProtobufCAllocator *allocator);
/* Messages__GetRequest methods */
void   messages__get_request__init
                     (Messages__GetRequest         *message);
size_t messages__get_request__get_packed_size
                     (const Messages__GetRequest   *message);
size_t messages__get_request__pack
                     (const Messages__GetRequest   *message,
                      uint8_t             *out);
size_t messages__get_request__pack_to_buffer
                     (const Messages__GetRequest   *message,
                      ProtobufCBuffer     *buffer);
Messages__GetRequest *
       messages__get_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   messages__get_request__free_unpacked
                     (Messages__GetRequest *message,
                      ProtobufCAllocator *allocator);
/* Messages__GetResponse methods */
void   messages__get_response__init
                     (Messages__GetResponse         *message);
size_t messages__get_response__get_packed_size
                     (const Messages__GetResponse   *message);
size_t messages__get_response__pack
                     (const Messages__GetResponse   *message,
                      uint8_t             *out);
size_t messages__get_response__pack_to_buffer
                     (const Messages__GetResponse   *message,
                      ProtobufCBuffer     *buffer);
Messages__GetResponse *
       messages__get_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   messages__get_response__free_unpacked
                     (Messages__GetResponse *message,
                      ProtobufCAllocator *allocator);
/* Messages__PutRequest methods */
void   messages__put_request__init
                     (Messages__PutRequest         *message);
size_t messages__put_request__get_packed_size
                     (const Messages__PutRequest   *message);
size_t messages__put_request__pack
                     (const Messages__PutRequest   *message,
                      uint8_t             *out);
size_t messages__put_request__pack_to_buffer
                     (const Messages__PutRequest   *message,
                      ProtobufCBuffer     *buffer);
Messages__PutRequest *
       messages__put_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   messages__put_request__free_unpacked
                     (Messages__PutRequest *message,
                      ProtobufCAllocator *allocator);
/* Messages__PutResponse methods */
void   messages__put_response__init
                     (Messages__PutResponse         *message);
size_t messages__put_response__get_packed_size
                     (const Messages__PutResponse   *message);
size_t messages__put_response__pack
                     (const Messages__PutResponse   *message,
                      uint8_t             *out);
size_t messages__put_response__pack_to_buffer
                     (const Messages__PutResponse   *message,
                      ProtobufCBuffer     *buffer);
Messages__PutResponse *
       messages__put_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   messages__put_response__free_unpacked
                     (Messages__PutResponse *message,
                      ProtobufCAllocator *allocator);
/* Messages__RemoveRequest methods */
void   messages__remove_request__init
                     (Messages__RemoveRequest         *message);
size_t messages__remove_request__get_packed_size
                     (const Messages__RemoveRequest   *message);
size_t messages__remove_request__pack
                     (const Messages__RemoveRequest   *message,
                      uint8_t             *out);
size_t messages__remove_request__pack_to_buffer
                     (const Messages__RemoveRequest   *message,
                      ProtobufCBuffer     *buffer);
Messages__RemoveRequest *
       messages__remove_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   messages__remove_request__free_unpacked
                     (Messages__RemoveRequest *message,
                      ProtobufCAllocator *allocator);
/* Messages__RemoveResponse methods */
void   messages__remove_response__init
                     (Messages__RemoveResponse         *message);
size_t messages__remove_response__get_packed_size
                     (const Messages__RemoveResponse   *message);
size_t messages__remove_response__pack
                     (const Messages__RemoveResponse   *message,
                      uint8_t             *out);
size_t messages__remove_response__pack_to_buffer
                     (const Messages__RemoveResponse   *message,
                      ProtobufCBuffer     *buffer);
Messages__RemoveResponse *
       messages__remove_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   messages__remove_response__free_unpacked
                     (Messages__RemoveResponse *message,
                      ProtobufCAllocator *allocator);
/* Messages__InitStackRequest methods */
void   messages__init_stack_request__init
                     (Messages__InitStackRequest         *message);
size_t messages__init_stack_request__get_packed_size
                     (const Messages__InitStackRequest   *message);
size_t messages__init_stack_request__pack
                     (const Messages__InitStackRequest   *message,
                      uint8_t             *out);
size_t messages__init_stack_request__pack_to_buffer
                     (const Messages__InitStackRequest   *message,
                      ProtobufCBuffer     *buffer);
Messages__InitStackRequest *
       messages__init_stack_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   messages__init_stack_request__free_unpacked
                     (Messages__InitStackRequest *message,
                      ProtobufCAllocator *allocator);
/* Messages__InitStackResponse methods */
void   messages__init_stack_response__init
                     (Messages__InitStackResponse         *message);
size_t messages__init_stack_response__get_packed_size
                     (const Messages__InitStackResponse   *message);
size_t messages__init_stack_response__pack
                     (const Messages__InitStackResponse   *message,
                      uint8_t             *out);
size_t messages__init_stack_response__pack_to_buffer
                     (const Messages__InitStackResponse   *message,
                      ProtobufCBuffer     *buffer);
Messages__InitStackResponse *
       messages__init_stack_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   messages__init_stack_response__free_unpacked
                     (Messages__InitStackResponse *message,
                      ProtobufCAllocator *allocator);
/* Messages__PushRequest methods */
void   messages__push_request__init
                     (Messages__PushRequest         *message);
size_t messages__push_request__get_packed_size
                     (const Messages__PushRequest   *message);
size_t messages__push_request__pack
                     (const Messages__PushRequest   *message,
                      uint8_t             *out);
size_t messages__push_request__pack_to_buffer
                     (const Messages__PushRequest   *message,
                      ProtobufCBuffer     *buffer);
Messages__PushRequest *
       messages__push_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   messages__push_request__free_unpacked
                     (Messages__PushRequest *message,
                      ProtobufCAllocator *allocator);
/* Messages__PushResponse methods */
void   messages__push_response__init
                     (Messages__PushResponse         *message);
size_t messages__push_response__get_packed_size
                     (const Messages__PushResponse   *message);
size_t messages__push_response__pack
                     (const Messages__PushResponse   *message,
                      uint8_t             *out);
size_t messages__push_response__pack_to_buffer
                     (const Messages__PushResponse   *message,
                      ProtobufCBuffer     *buffer);
Messages__PushResponse *
       messages__push_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   messages__push_response__free_unpacked
                     (Messages__PushResponse *message,
                      ProtobufCAllocator *allocator);
/* Messages__PopRequest methods */
void   messages__pop_request__init
                     (Messages__PopRequest         *message);
size_t messages__pop_request__get_packed_size
                     (const Messages__PopRequest   *message);
size_t messages__pop_request__pack
                     (const Messages__PopRequest   *message,
                      uint8_t             *out);
size_t messages__pop_request__pack_to_buffer
                     (const Messages__PopRequest   *message,
                      ProtobufCBuffer     *buffer);
Messages__PopRequest *
       messages__pop_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   messages__pop_request__free_unpacked
                     (Messages__PopRequest *message,
                      ProtobufCAllocator *allocator);
/* Messages__PopResponse methods */
void   messages__pop_response__init
                     (Messages__PopResponse         *message);
size_t messages__pop_response__get_packed_size
                     (const Messages__PopResponse   *message);
size_t messages__pop_response__pack
                     (const Messages__PopResponse   *message,
                      uint8_t             *out);
size_t messages__pop_response__pack_to_buffer
                     (const Messages__PopResponse   *message,
                      ProtobufCBuffer     *buffer);
Messages__PopResponse *
       messages__pop_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   messages__pop_response__free_unpacked
                     (Messages__PopResponse *message,
                      ProtobufCAllocator *allocator);
/* Messages__InitQueueRequest methods */
void   messages__init_queue_request__init
                     (Messages__InitQueueRequest         *message);
size_t messages__init_queue_request__get_packed_size
                     (const Messages__InitQueueRequest   *message);
size_t messages__init_queue_request__pack
                     (const Messages__InitQueueRequest   *message,
                      uint8_t             *out);
size_t messages__init_queue_request__pack_to_buffer
                     (const Messages__InitQueueRequest   *message,
                      ProtobufCBuffer     *buffer);
Messages__InitQueueRequest *
       messages__init_queue_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   messages__init_queue_request__free_unpacked
                     (Messages__InitQueueRequest *message,
                      ProtobufCAllocator *allocator);
/* Messages__InitQueueResponse methods */
void   messages__init_queue_response__init
                     (Messages__InitQueueResponse         *message);
size_t messages__init_queue_response__get_packed_size
                     (const Messages__InitQueueResponse   *message);
size_t messages__init_queue_response__pack
                     (const Messages__InitQueueResponse   *message,
                      uint8_t             *out);
size_t messages__init_queue_response__pack_to_buffer
                     (const Messages__InitQueueResponse   *message,
                      ProtobufCBuffer     *buffer);
Messages__InitQueueResponse *
       messages__init_queue_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   messages__init_queue_response__free_unpacked
                     (Messages__InitQueueResponse *message,
                      ProtobufCAllocator *allocator);
/* Messages__EnqueueRequest methods */
void   messages__enqueue_request__init
                     (Messages__EnqueueRequest         *message);
size_t messages__enqueue_request__get_packed_size
                     (const Messages__EnqueueRequest   *message);
size_t messages__enqueue_request__pack
                     (const Messages__EnqueueRequest   *message,
                      uint8_t             *out);
size_t messages__enqueue_request__pack_to_buffer
                     (const Messages__EnqueueRequest   *message,
                      ProtobufCBuffer     *buffer);
Messages__EnqueueRequest *
       messages__enqueue_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   messages__enqueue_request__free_unpacked
                     (Messages__EnqueueRequest *message,
                      ProtobufCAllocator *allocator);
/* Messages__EnqueueResponse methods */
void   messages__enqueue_response__init
                     (Messages__EnqueueResponse         *message);
size_t messages__enqueue_response__get_packed_size
                     (const Messages__EnqueueResponse   *message);
size_t messages__enqueue_response__pack
                     (const Messages__EnqueueResponse   *message,
                      uint8_t             *out);
size_t messages__enqueue_response__pack_to_buffer
                     (const Messages__EnqueueResponse   *message,
                      ProtobufCBuffer     *buffer);
Messages__EnqueueResponse *
       messages__enqueue_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   messages__enqueue_response__free_unpacked
                     (Messages__EnqueueResponse *message,
                      ProtobufCAllocator *allocator);
/* Messages__DequeueRequest methods */
void   messages__dequeue_request__init
                     (Messages__DequeueRequest         *message);
size_t messages__dequeue_request__get_packed_size
                     (const Messages__DequeueRequest   *message);
size_t messages__dequeue_request__pack
                     (const Messages__DequeueRequest   *message,
                      uint8_t             *out);
size_t messages__dequeue_request__pack_to_buffer
                     (const Messages__DequeueRequest   *message,
                      ProtobufCBuffer     *buffer);
Messages__DequeueRequest *
       messages__dequeue_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   messages__dequeue_request__free_unpacked
                     (Messages__DequeueRequest *message,
                      ProtobufCAllocator *allocator);
/* Messages__DequeueResponse methods */
void   messages__dequeue_response__init
                     (Messages__DequeueResponse         *message);
size_t messages__dequeue_response__get_packed_size
                     (const Messages__DequeueResponse   *message);
size_t messages__dequeue_response__pack
                     (const Messages__DequeueResponse   *message,
                      uint8_t             *out);
size_t messages__dequeue_response__pack_to_buffer
                     (const Messages__DequeueResponse   *message,
                      ProtobufCBuffer     *buffer);
Messages__DequeueResponse *
       messages__dequeue_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   messages__dequeue_response__free_unpacked
                     (Messages__DequeueResponse *message,
                      ProtobufCAllocator *allocator);
/* Messages__PeekRequest methods */
void   messages__peek_request__init
                     (Messages__PeekRequest         *message);
size_t messages__peek_request__get_packed_size
                     (const Messages__PeekRequest   *message);
size_t messages__peek_request__pack
                     (const Messages__PeekRequest   *message,
                      uint8_t             *out);
size_t messages__peek_request__pack_to_buffer
                     (const Messages__PeekRequest   *message,
                      ProtobufCBuffer     *buffer);
Messages__PeekRequest *
       messages__peek_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   messages__peek_request__free_unpacked
                     (Messages__PeekRequest *message,
                      ProtobufCAllocator *allocator);
/* Messages__PeekResponse methods */
void   messages__peek_response__init
                     (Messages__PeekResponse         *message);
size_t messages__peek_response__get_packed_size
                     (const Messages__PeekResponse   *message);
size_t messages__peek_response__pack
                     (const Messages__PeekResponse   *message,
                      uint8_t             *out);
size_t messages__peek_response__pack_to_buffer
                     (const Messages__PeekResponse   *message,
                      ProtobufCBuffer     *buffer);
Messages__PeekResponse *
       messages__peek_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   messages__peek_response__free_unpacked
                     (Messages__PeekResponse *message,
                      ProtobufCAllocator *allocator);
/* Messages__SizeRequest methods */
void   messages__size_request__init
                     (Messages__SizeRequest         *message);
size_t messages__size_request__get_packed_size
                     (const Messages__SizeRequest   *message);
size_t messages__size_request__pack
                     (const Messages__SizeRequest   *message,
                      uint8_t             *out);
size_t messages__size_request__pack_to_buffer
                     (const Messages__SizeRequest   *message,
                      ProtobufCBuffer     *buffer);
Messages__SizeRequest *
       messages__size_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   messages__size_request__free_unpacked
                     (Messages__SizeRequest *message,
                      ProtobufCAllocator *allocator);
/* Messages__SizeResponse methods */
void   messages__size_response__init
                     (Messages__SizeResponse         *message);
size_t messages__size_response__get_packed_size
                     (const Messages__SizeResponse   *message);
size_t messages__size_response__pack
                     (const Messages__SizeResponse   *message,
                      uint8_t             *out);
size_t messages__size_response__pack_to_buffer
                     (const Messages__SizeResponse   *message,
                      ProtobufCBuffer     *buffer);
Messages__SizeResponse *
       messages__size_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   messages__size_response__free_unpacked
                     (Messages__SizeResponse *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*Messages__Value_Closure)
                 (const Messages__Value *message,
                  void *closure_data);
typedef void (*Messages__GetRequest_Closure)
                 (const Messages__GetRequest *message,
                  void *closure_data);
typedef void (*Messages__GetResponse_Closure)
                 (const Messages__GetResponse *message,
                  void *closure_data);
typedef void (*Messages__PutRequest_Closure)
                 (const Messages__PutRequest *message,
                  void *closure_data);
typedef void (*Messages__PutResponse_Closure)
                 (const Messages__PutResponse *message,
                  void *closure_data);
typedef void (*Messages__RemoveRequest_Closure)
                 (const Messages__RemoveRequest *message,
                  void *closure_data);
typedef void (*Messages__RemoveResponse_Closure)
                 (const Messages__RemoveResponse *message,
                  void *closure_data);
typedef void (*Messages__InitStackRequest_Closure)
                 (const Messages__InitStackRequest *message,
                  void *closure_data);
typedef void (*Messages__InitStackResponse_Closure)
                 (const Messages__InitStackResponse *message,
                  void *closure_data);
typedef void (*Messages__PushRequest_Closure)
                 (const Messages__PushRequest *message,
                  void *closure_data);
typedef void (*Messages__PushResponse_Closure)
                 (const Messages__PushResponse *message,
                  void *closure_data);
typedef void (*Messages__PopRequest_Closure)
                 (const Messages__PopRequest *message,
                  void *closure_data);
typedef void (*Messages__PopResponse_Closure)
                 (const Messages__PopResponse *message,
                  void *closure_data);
typedef void (*Messages__InitQueueRequest_Closure)
                 (const Messages__InitQueueRequest *message,
                  void *closure_data);
typedef void (*Messages__InitQueueResponse_Closure)
                 (const Messages__InitQueueResponse *message,
                  void *closure_data);
typedef void (*Messages__EnqueueRequest_Closure)
                 (const Messages__EnqueueRequest *message,
                  void *closure_data);
typedef void (*Messages__EnqueueResponse_Closure)
                 (const Messages__EnqueueResponse *message,
                  void *closure_data);
typedef void (*Messages__DequeueRequest_Closure)
                 (const Messages__DequeueRequest *message,
                  void *closure_data);
typedef void (*Messages__DequeueResponse_Closure)
                 (const Messages__DequeueResponse *message,
                  void *closure_data);
typedef void (*Messages__PeekRequest_Closure)
                 (const Messages__PeekRequest *message,
                  void *closure_data);
typedef void (*Messages__PeekResponse_Closure)
                 (const Messages__PeekResponse *message,
                  void *closure_data);
typedef void (*Messages__SizeRequest_Closure)
                 (const Messages__SizeRequest *message,
                  void *closure_data);
typedef void (*Messages__SizeResponse_Closure)
                 (const Messages__SizeResponse *message,
                  void *closure_data);

/* --- services --- */

typedef struct _Messages__Database_Service Messages__Database_Service;
struct _Messages__Database_Service
{
  ProtobufCService base;
  void (*get)(Messages__Database_Service *service,
              const Messages__GetRequest *input,
              Messages__GetResponse_Closure closure,
              void *closure_data);
  void (*put)(Messages__Database_Service *service,
              const Messages__PutRequest *input,
              Messages__PutResponse_Closure closure,
              void *closure_data);
  void (*remove)(Messages__Database_Service *service,
                 const Messages__RemoveRequest *input,
                 Messages__RemoveResponse_Closure closure,
                 void *closure_data);
  void (*push)(Messages__Database_Service *service,
               const Messages__PushRequest *input,
               Messages__PushResponse_Closure closure,
               void *closure_data);
  void (*pop)(Messages__Database_Service *service,
              const Messages__PopRequest *input,
              Messages__PopResponse_Closure closure,
              void *closure_data);
  void (*enqueue)(Messages__Database_Service *service,
                  const Messages__EnqueueRequest *input,
                  Messages__EnqueueResponse_Closure closure,
                  void *closure_data);
  void (*dequeue)(Messages__Database_Service *service,
                  const Messages__DequeueRequest *input,
                  Messages__DequeueResponse_Closure closure,
                  void *closure_data);
  void (*peek)(Messages__Database_Service *service,
               const Messages__PeekRequest *input,
               Messages__PeekResponse_Closure closure,
               void *closure_data);
  void (*size)(Messages__Database_Service *service,
               const Messages__SizeRequest *input,
               Messages__SizeResponse_Closure closure,
               void *closure_data);
};
typedef void (*Messages__Database_ServiceDestroy)(Messages__Database_Service *);
void messages__database__init (Messages__Database_Service *service,
                               Messages__Database_ServiceDestroy destroy);
#define MESSAGES__DATABASE__BASE_INIT \
    { &messages__database__descriptor, protobuf_c_service_invoke_internal, NULL }
#define MESSAGES__DATABASE__INIT(function_prefix__) \
    { MESSAGES__DATABASE__BASE_INIT,\
      function_prefix__ ## get,\
      function_prefix__ ## put,\
      function_prefix__ ## remove,\
      function_prefix__ ## push,\
      function_prefix__ ## pop,\
      function_prefix__ ## enqueue,\
      function_prefix__ ## dequeue,\
      function_prefix__ ## peek,\
      function_prefix__ ## size  }
void messages__database__get(ProtobufCService *service,
                             const Messages__GetRequest *input,
                             Messages__GetResponse_Closure closure,
                             void *closure_data);
void messages__database__put(ProtobufCService *service,
                             const Messages__PutRequest *input,
                             Messages__PutResponse_Closure closure,
                             void *closure_data);
void messages__database__remove(ProtobufCService *service,
                                const Messages__RemoveRequest *input,
                                Messages__RemoveResponse_Closure closure,
                                void *closure_data);
void messages__database__push(ProtobufCService *service,
                              const Messages__PushRequest *input,
                              Messages__PushResponse_Closure closure,
                              void *closure_data);
void messages__database__pop(ProtobufCService *service,
                             const Messages__PopRequest *input,
                             Messages__PopResponse_Closure closure,
                             void *closure_data);
void messages__database__enqueue(ProtobufCService *service,
                                 const Messages__EnqueueRequest *input,
                                 Messages__EnqueueResponse_Closure closure,
                                 void *closure_data);
void messages__database__dequeue(ProtobufCService *service,
                                 const Messages__DequeueRequest *input,
                                 Messages__DequeueResponse_Closure closure,
                                 void *closure_data);
void messages__database__peek(ProtobufCService *service,
                              const Messages__PeekRequest *input,
                              Messages__PeekResponse_Closure closure,
                              void *closure_data);
void messages__database__size(ProtobufCService *service,
                              const Messages__SizeRequest *input,
                              Messages__SizeResponse_Closure closure,
                              void *closure_data);

/* --- descriptors --- */

extern const ProtobufCEnumDescriptor    messages__error__descriptor;
extern const ProtobufCMessageDescriptor messages__value__descriptor;
extern const ProtobufCMessageDescriptor messages__get_request__descriptor;
extern const ProtobufCMessageDescriptor messages__get_response__descriptor;
extern const ProtobufCMessageDescriptor messages__put_request__descriptor;
extern const ProtobufCMessageDescriptor messages__put_response__descriptor;
extern const ProtobufCMessageDescriptor messages__remove_request__descriptor;
extern const ProtobufCMessageDescriptor messages__remove_response__descriptor;
extern const ProtobufCMessageDescriptor messages__init_stack_request__descriptor;
extern const ProtobufCMessageDescriptor messages__init_stack_response__descriptor;
extern const ProtobufCMessageDescriptor messages__push_request__descriptor;
extern const ProtobufCMessageDescriptor messages__push_response__descriptor;
extern const ProtobufCMessageDescriptor messages__pop_request__descriptor;
extern const ProtobufCMessageDescriptor messages__pop_response__descriptor;
extern const ProtobufCMessageDescriptor messages__init_queue_request__descriptor;
extern const ProtobufCMessageDescriptor messages__init_queue_response__descriptor;
extern const ProtobufCMessageDescriptor messages__enqueue_request__descriptor;
extern const ProtobufCMessageDescriptor messages__enqueue_response__descriptor;
extern const ProtobufCMessageDescriptor messages__dequeue_request__descriptor;
extern const ProtobufCMessageDescriptor messages__dequeue_response__descriptor;
extern const ProtobufCMessageDescriptor messages__peek_request__descriptor;
extern const ProtobufCMessageDescriptor messages__peek_response__descriptor;
extern const ProtobufCMessageDescriptor messages__size_request__descriptor;
extern const ProtobufCMessageDescriptor messages__size_response__descriptor;
extern const ProtobufCServiceDescriptor messages__database__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_messages_2eproto__INCLUDED */
